name: WhitelistByTime
main: ru.nightmirror.wlbytime.WhitelistByTimeImpl
version: '${version}'
author: NightMirror
description: Adding a player to the whitelist for a time
api-version: 1.16
folia-supported: true
softdepend:
  - PlaceholderAPI
commands:
  whitelist:
    usage: /whitelist help
    aliases: wl
permissions:
  whitelistbytime.add:
    default: op
  whitelistbytime.remove:
    default: op
  whitelistbytime.check:
    default: op
  whitelistbytime.checkme:
    default: op
  whitelistbytime.reload:
    default: op
  whitelistbytime.getall:
    default: op
  whitelistbytime.time:
    default: op
  whitelistbytime.turn:
    default: op
  whitelistbytime.help:
    default: op